baseURL = 'https://ccchamber.github.io/CCChamber.github.io/'
languageCode = 'de-de'
title = 'Colins Resume'
theme = 'hugo-resume'

[params]
address = "Oldenburg, DE"
email = "colin.kammer@yahoo.de"
favicon = "/favicon.ico"
firstName = "Colin"
lastName = "Kammer"
phone = ""
profileImage = "img/TechChat.png"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = false
showSkills = true